## LINCS MOA classifcation for prostate tissue using Feed Forward Neural Network

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [2]:
file_prostate=pd.read_hdf("/Users/Rashid/Desktop/Rashid/Career/PhD/Research/projects/GCN/data/GSE92742_fully_restricted_prostate.hdf")

In [3]:
df_prostate=file_prostate.reset_index(level=[0,1,2,3,4,5,6]) #change from multi index to single index

In [4]:
prostate_y=df_prostate["moa"].values #change moa column to numpy array
df_prostate= df_prostate.drop(columns=["pert_id","pert_name","cell_id","primary_site","subtype","moa","Fold"])
prostate_X=df_prostate.values #get the matrix of feature values for 978 genes


In [5]:
labels,uniques=pd.factorize(prostate_y) #labels are the encodings
prostate_y=labels

In [6]:
sc=StandardScaler()
prostate_X=sc.fit_transform(prostate_X) #normalize feature data

In [7]:
#SPLIT DATA
X_train,X_test,y_train,y_test=train_test_split(prostate_X,prostate_y,test_size=0.2,random_state=42)#split into train and test

In [8]:
mlpc=MLPClassifier(hidden_layer_sizes=(997),max_iter=350) #max_iter goes through the layers 350 times(forward pass and backpropagation) to adjust weights
mlpc.fit(X_train,y_train)
pred_mlpc=mlpc.predict(X_test) #around 5 mins tops

In [9]:
#METRICS
print(confusion_matrix(y_test,pred_mlpc))
print(classification_report(y_test,pred_mlpc))
acc_mlpc=accuracy_score(y_test,pred_mlpc) #result for svm
print(acc_mlpc) #print precision score 
#results matches in the paper where accuracy is 68.3 ± 0.60, macro F1 is 50.4 ± 0.71. Took 4-5 minutes on macbook pro 2.7 GHz inter core i5 processor, 16 GB 1867 MHz DDR3 Memomry, Intel Iris Graphics 6100 1536 MB Graphics

[[  41    1   37   11   16    7   11  113    2]
 [   7  190    1    2    2    5    3   12    0]
 [  29    4  192   36   20   12   24  107    4]
 [  20    3   34   29   15    4    9  104    1]
 [  22    1   14   14   29    9   11  104    0]
 [  10    4   16    3    9  787    9   88    1]
 [   8    1    5    5    5   14  683  114   67]
 [  52   11   54   35   47   37   85 1413   12]
 [   1    0    2    0    1    2  141   12   67]]
              precision    recall  f1-score   support

           0       0.22      0.17      0.19       239
           1       0.88      0.86      0.87       222
           2       0.54      0.45      0.49       428
           3       0.21      0.13      0.16       219
           4       0.20      0.14      0.17       204
           5       0.90      0.85      0.87       927
           6       0.70      0.76      0.73       902
           7       0.68      0.81      0.74      1746
           8       0.44      0.30      0.35       226

    accuracy             