## LINCS MOA Classifcation using support vector machine

In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import train_test_split
#from sklearn.svm import SVC
from sklearn import svm
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [2]:
file_prostate=pd.read_hdf("/Users/Rashid/Desktop/Rashid/Career/PhD/Research/projects/GCN/data/GSE92742_fully_restricted_prostate.hdf")

In [3]:
df_prostate=file_prostate.reset_index(level=[0,1,2,3,4,5,6]) #change from multi index to single index

In [4]:
prostate_y=df_prostate["moa"].values #change moa column to numpy array
df_prostate= df_prostate.drop(columns=["pert_id","pert_name","cell_id","primary_site","subtype","moa","Fold"])
prostate_X=df_prostate.values #get the matrix of feature values for 978 genes


In [5]:
labels,uniques=pd.factorize(prostate_y) #labels are the encodings
prostate_y=labels

In [6]:
sc=StandardScaler()
prostate_X=sc.fit_transform(prostate_X) #normalize feature data

In [7]:
#SPLIT DATA
X_train,X_test,y_train,y_test=train_test_split(prostate_X,prostate_y,test_size=0.2,random_state=42)#split into train and test

In [10]:
clm=svm.SVC()
clm.fit(X_train,y_train) #fit SVM with training data. took around 10 mins on mac


/anaconda3/envs/scikitLearnTutorial/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


NameError: name 'rfc' is not defined

In [11]:
pred_clm=clm.predict(X_test) #see how the test data is predicted
#METRICS
print(confusion_matrix(y_test,pred_clm))
print(classification_report(y_test,pred_clm))
acc_clm=accuracy_score(y_test,pred_clm) #result for svm
print(acc_clm) #print precision score 
#results matches in the paper where accuracy is 66.61, macro F1 is 0.43. Took 4-5 minutes on macbook pro 2.7 GHz inter core i5 processor, 16 GB 1867 MHz DDR3 Memomry, Intel Iris Graphics 6100 1536 MB Graphics

[[   2    1   11    0    0    3    3  219    0]
 [   0  160    2    0    0    2    1   57    0]
 [   1    1  145    2    0    9   12  258    0]
 [   0    0   24    1    0    2    6  186    0]
 [   0    0    1    0    3    1    2  197    0]
 [   0    0    7    0    0  673    7  240    0]
 [   0    0    1    0    1    2  662  235    1]
 [   0    1    1    0    1    5   25 1713    0]
 [   0    0    0    0    0    0  193   27    6]]
              precision    recall  f1-score   support

           0       0.67      0.01      0.02       239
           1       0.98      0.72      0.83       222
           2       0.76      0.34      0.47       428
           3       0.33      0.00      0.01       219
           4       0.60      0.01      0.03       204
           5       0.97      0.73      0.83       927
           6       0.73      0.73      0.73       902
           7       0.55      0.98      0.70      1746
           8       0.86      0.03      0.05       226

    accuracy             